## Data 결합

In [58]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [59]:
ar1 = np.arange(4)
ar1

array([0, 1, 2, 3])

In [61]:
ar1 = np.arange(4).reshape(2,2)

In [62]:
ar1

array([[0, 1],
       [2, 3]])

In [68]:
np.concatenate([ar1,ar1], axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [115]:
df1 = DataFrame({
    'A':[1,2,3],
    'B':[4,5,6]
})

In [116]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [98]:
df2 = DataFrame({
    'A':[10,11],
    'B':[40,50]
})

In [99]:
df2

A   B
0  10  40
1  11  50

In [100]:
df3 = DataFrame({
    'A':[40,50,60],
    'B':[70,80,90],
    'C':[10,11,12]
})

In [101]:
df3

A   B   C
0  40  70  10
1  50  80  11
2  60  90  12

In [103]:
pd.concat([df1,df2])

A   B
0   1   4
1   2   5
2   3   6
0  10  40
1  11  50

In [105]:
pd.concat([df1,df2],axis=1)

A  B     A     B
0  1  4  10.0  40.0
1  2  5  11.0  50.0
2  3  6   NaN   NaN

In [107]:
pd.concat([df1,df2],axis =1,join='inner')

A  B   A   B
0  1  4  10  40
1  2  5  11  50

In [117]:
pd.concat([df1,df2],axis =0,join='inner', keys=['ONE', 'TWO'])

A   B
ONE 0   1   4
    1   2   5
    2   3   6
TWO 0  10  40
    1  11  50

In [136]:
df1 = DataFrame({'A':[1,2,3,4],'B':[5,6,7,8],'C':[9,10,11,12]})

In [137]:
df1

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [138]:
df2 = DataFrame({'A':['a','b','c','d'],'D':['e','f','g','h'],'E':['i','j','k','l']})

In [139]:
df2

A  D  E
0  a  e  i
1  b  f  j
2  c  g  k
3  d  h  l

In [140]:
df1.combine_first(df2)

A  B   C  D  E
0  1  5   9  e  i
1  2  6  10  f  j
2  3  7  11  g  k
3  4  8  12  h  l

In [25]:
list_1 = [1,2,3,4]

In [26]:
a = np.array(list_1)

In [27]:
a

array([1, 2, 3, 4])

In [28]:
b = np.array([[1,2,3],[4,5,6]])

In [29]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
print(b.shape)

(2, 3)


In [31]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [33]:
arr = np.array(lst)

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
## a = arr[1:, 1:]
a

array([1, 2, 3, 4])

In [36]:
## a = arr[0:,2:]
a

array([1, 2, 3, 4])

In [37]:
## a = arr [0:2, 0:2]
print(a)

[1 2 3 4]


In [38]:
bool_array = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])

In [42]:
n = a[bool_array];
print(n)

[2 4 6 8]


In [40]:
a = np.array(lst)
bool_indexing = (a % 2 ==0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [46]:
print(a[bool_indexing])
n = a[ a % 2 == 0]

[2 4 6 8]


In [48]:
a = np.arange(4)
b = np.arange(4,8)

In [49]:
a

array([0, 1, 2, 3])

In [50]:
b

array([4, 5, 6, 7])

In [51]:
c = a + b
c = np.add(a,b)
print(c)

[ 4  6  8 10]


In [54]:
c = a - b
c = np.subtract(a,b)
print(c)

[-4 -4 -4 -4]


In [56]:
c = a * b
c = np.multiply(a,b)
print(c)

[ 0  5 12 21]


In [57]:
c = a / b
c = np.divide(a,b)
print(c)

[0.         0.2        0.33333333 0.42857143]
